[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/generate-names"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
