[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  external_node_modules = ["replicate"]

[dev]
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/generate-names"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
